# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3a25407d2c2cbcfdb7f41dfc5f36137de10faea5c528531fbaf7a330184871ebade5ea826e3ef4471b6de0720e008fbc55134daa8132090a7358c22365aecfa

test:
  secret_key_base: cb6af31ad39b84fe85acd7d3e6e59e5945d33c3a4c9a8828df8fee0f59ee36e495392dbd9257a4ffa58c3fe2b401dfcd5434f08ebc3a4cfd7c171a6e3a2ae49c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
